# Generated by Django 4.2.11 on 2024-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='device_group_relationship_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='device_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device', models.CharField(max_length=50)),
                ('expand', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='function_group_relationship_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=50)),
                ('group_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='function_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('func', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='group_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='result_notes_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=100)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('confirm', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='result_overall_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('jixian', models.BooleanField()),
                ('result', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='result_specific_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('device', models.CharField(max_length=50)),
                ('command', models.CharField(max_length=100)),
                ('result', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
