# Generated by Django 4.2.11 on 2026-07-21 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompliancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='策略名称')),
                ('description', models.TextField(blank=True, default='', verbose_name='说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '合规策略',
            },
        ),
        migrations.AddField(
            model_name='checkitem',
            name='severity',
            field=models.CharField(choices=[('P0', 'P0-高危'), ('P1', 'P1-中危'), ('P2', 'P2-低危')], default='P2', help_text='该巡检项判定异常时记录的严重级别', max_length=10, verbose_name='严重级别'),
        ),
        migrations.AddField(
            model_name='checkresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间'),
        ),
        migrations.CreateModel(
            name='DiscoveryRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='发现时间')),
                ('device', models.CharField(max_length=50, verbose_name='本端设备')),
                ('neighbor', models.CharField(blank=True, default='', max_length=80, verbose_name='邻居设备名')),
                ('neighbor_ip', models.CharField(blank=True, default='', max_length=50, verbose_name='邻居管理IP')),
                ('local_port', models.CharField(blank=True, default='', max_length=50, verbose_name='本端端口')),
                ('peer_port', models.CharField(blank=True, default='', max_length=50, verbose_name='对端端口')),
                ('is_known', models.BooleanField(default=False, verbose_name='是否已知资产')),
                ('site', models.CharField(blank=True, default='', max_length=20, verbose_name='站点')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '设备发现记录',
                'indexes': [models.Index(fields=['time', 'device'], name='app02_disco_time_1bf013_idx')],
            },
        ),
        migrations.CreateModel(
            name='ComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('source_command', models.CharField(help_text='取值自哪条命令的采集结果(如 display current-configuration)', max_length=200, verbose_name='数据源命令')),
                ('rule_type', models.CharField(choices=[('regex', '正则必须匹配'), ('contains', '必须包含'), ('absence', '不应出现')], default='contains', max_length=20, verbose_name='判定方式')),
                ('pattern', models.CharField(blank=True, default='', max_length=400, verbose_name='匹配内容/正则')),
                ('severity', models.CharField(choices=[('P0', 'P0-高危'), ('P1', 'P1-中危'), ('P2', 'P2-低危')], default='P2', max_length=10, verbose_name='严重级别')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='不合规说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='app02.compliancepolicy', verbose_name='所属策略')),
            ],
            options={
                'verbose_name': '合规规则',
            },
        ),
        migrations.CreateModel(
            name='ComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='检查时间')),
                ('device', models.CharField(max_length=50, verbose_name='设备名')),
                ('policy', models.CharField(max_length=100, verbose_name='策略')),
                ('rule', models.CharField(max_length=100, verbose_name='规则')),
                ('passed', models.BooleanField(default=True, verbose_name='是否合规')),
                ('detail', models.TextField(blank=True, default='', verbose_name='详情')),
                ('severity', models.CharField(choices=[('P0', 'P0-高危'), ('P1', 'P1-中危'), ('P2', 'P2-低危')], default='P2', max_length=10, verbose_name='严重级别')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='入库时间')),
            ],
            options={
                'verbose_name': '合规结果',
                'indexes': [models.Index(fields=['time', 'device'], name='app02_compl_time_7c7eb3_idx')],
            },
        ),
    ]
