# Generated by Django 4.2.11 on 2024-07-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_table',
            name='ip',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_table',
            name='password',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device_table',
            name='user',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
