# Generated by Django 4.2.11 on 2024-07-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_device_table_ip_device_table_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_table',
            name='group_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
