# Generated by Django 4.2.11 on 2026-07-21 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0002_compliancepolicy_checkitem_severity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='设备名')),
                ('site', models.CharField(blank=True, default='', max_length=20, verbose_name='站点')),
                ('vendor', models.CharField(blank=True, default='H3C', max_length=30, verbose_name='厂商')),
                ('model', models.CharField(blank=True, default='', max_length=60, verbose_name='型号')),
                ('os_version', models.CharField(blank=True, default='', max_length=80, verbose_name='软件版本')),
                ('serial', models.CharField(blank=True, default='', max_length=60, verbose_name='序列号')),
                ('uptime_days', models.IntegerField(blank=True, null=True, verbose_name='运行天数')),
                ('mgmt_ip', models.CharField(blank=True, default='', max_length=40, verbose_name='管理IP')),
                ('role', models.CharField(blank=True, default='', max_length=20, verbose_name='角色')),
                ('cpu_5s', models.FloatField(blank=True, null=True, verbose_name='CPU(5s)%')),
                ('mem_free_ratio', models.FloatField(blank=True, null=True, verbose_name='内存空闲%')),
                ('last_sync', models.DateTimeField(auto_now=True, null=True, verbose_name='最近同步')),
            ],
            options={
                'verbose_name': 'CMDB设备',
                'ordering': ['site', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CmdbSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='同步时间')),
                ('site', models.CharField(blank=True, default='', max_length=20, verbose_name='站点')),
                ('device_count', models.IntegerField(default=0, verbose_name='设备数')),
                ('note', models.TextField(blank=True, default='', verbose_name='说明')),
            ],
            options={
                'verbose_name': 'CMDB同步日志',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='CmdbVlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_id', models.IntegerField(verbose_name='VLAN ID')),
                ('name', models.CharField(blank=True, default='', max_length=40, verbose_name='VLAN名')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vlans', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB VLAN',
                'unique_together': {('device', 'vlan_id')},
            },
        ),
        migrations.CreateModel(
            name='CmdbNeighborLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_port', models.CharField(blank=True, default='', max_length=40, verbose_name='本端端口')),
                ('peer_device', models.CharField(blank=True, default='', max_length=80, verbose_name='对端设备')),
                ('peer_port', models.CharField(blank=True, default='', max_length=40, verbose_name='对端端口')),
                ('protocol', models.CharField(blank=True, default='lldp', max_length=10, verbose_name='协议')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='app02.cmdbdevice', verbose_name='本端设备')),
            ],
            options={
                'verbose_name': 'CMDB链路',
                'unique_together': {('device', 'local_port', 'peer_device', 'peer_port')},
            },
        ),
        migrations.CreateModel(
            name='CmdbIpSubnet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(blank=True, default='', max_length=40, verbose_name='接口')),
                ('cidr', models.CharField(blank=True, default='', max_length=48, verbose_name='IP/CIDR')),
                ('vrf', models.CharField(blank=True, default='', max_length=30, verbose_name='VRF')),
                ('gateway', models.CharField(blank=True, default='', max_length=40, verbose_name='网关')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ips', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB IP',
                'unique_together': {('device', 'interface_name', 'cidr')},
            },
        ),
        migrations.CreateModel(
            name='CmdbInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='接口名')),
                ('admin_status', models.CharField(blank=True, default='', max_length=12, verbose_name='管理状态')),
                ('oper_status', models.CharField(blank=True, default='', max_length=12, verbose_name='操作状态')),
                ('speed_mbps', models.IntegerField(blank=True, null=True, verbose_name='速率Mbps')),
                ('duplex', models.CharField(blank=True, default='', max_length=10, verbose_name='双工')),
                ('mtu', models.IntegerField(blank=True, null=True, verbose_name='MTU')),
                ('port_mode', models.CharField(blank=True, default='', max_length=10, verbose_name='端口模式')),
                ('description', models.CharField(blank=True, default='', max_length=120, verbose_name='描述')),
                ('mac', models.CharField(blank=True, default='', max_length=20, verbose_name='MAC')),
                ('vlan_id', models.IntegerField(blank=True, null=True, verbose_name='VLAN')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB接口',
                'unique_together': {('device', 'name')},
            },
        ),
    ]
