# Generated by Django 4.2.11 on 2026-07-21 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0003_cmdbdevice_cmdbsynclog_cmdbvlan_cmdbneighborlink_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkitem',
            name='compare_strip',
            field=models.JSONField(blank=True, help_text='对比差异前清洗文本(JSON)：{"head_lines":3,"skip_patterns":["^2026-"]}', null=True, verbose_name='对比清洗配置'),
        ),
        migrations.AddField(
            model_name='checkitem',
            name='extract_parser',
            field=models.CharField(blank=True, choices=[('', '不提取'), ('memory', '内存提取')], default='', help_text='对比页结构化展示该命令提取的字段（仅展示，不影响判定）', max_length=30, verbose_name='字段提取器'),
        ),
    ]
