# Generated by Django 4.2.11 on 2026-07-21 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_checkitem_compare_strip_checkitem_extract_parser'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckerScript',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='函数名(对应 checker_config.func)')),
                ('source', models.TextField(verbose_name='源码(def func(parsed, baseline, config, extra): ...)')),
                ('version', models.IntegerField(default=1, verbose_name='当前版本')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用(DB覆盖优先)')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'Checker源码',
                'verbose_name_plural': 'Checker源码',
            },
        ),
        migrations.CreateModel(
            name='CheckerScriptVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(verbose_name='版本号')),
                ('source', models.TextField(verbose_name='源码')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='app02.checkerscript', verbose_name='源码')),
            ],
            options={
                'verbose_name': 'Checker源码版本',
                'verbose_name_plural': 'Checker源码版本',
                'ordering': ['-version'],
            },
        ),
    ]
