# Generated by Django 4.2.11 on 2024-08-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0004_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_checkbox_field', models.BooleanField(default=False)),
            ],
        ),
    ]
