# Generated by Django 4.2.11 on 2024-08-01 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0005_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='device_table',
            name='device_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
