# Generated by Django 4.2.11 on 2026-07-23 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_deviceparseresult'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='deviceparseresult',
            new_name='app02_devic_device_66ec55_idx',
            old_name='dpr_dev_cmd_time_idx',
        ),
    ]
