# Generated by Django 4.2.11 on 2024-08-06 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0006_device_table_device_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device_table',
            name='expand',
            field=models.TextField(),
        ),
    ]
