# Generated by Django 4.2.11 on 2026-07-24 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0007_rename_dpr_dev_cmd_time_idx_app02_devic_device_66ec55_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['device'], name='app02_check_device_7b5a93_idx'),
        ),
        migrations.AddIndex(
            model_name='checkresult',
            index=models.Index(fields=['created_at'], name='app02_check_created_02416c_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceparseresult',
            index=models.Index(fields=['created_at'], name='app02_devic_created_cbcdbe_idx'),
        ),
    ]
