# Generated by Django 4.2.11 on 2026-07-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0008_checkresult_app02_check_device_7b5a93_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='xunjianrecord',
            name='expected_count',
            field=models.IntegerField(default=0, verbose_name='应执行项数'),
        ),
    ]
