# Generated by Django 4.2.11 on 2024-08-14 08:21

import app02.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0008_rename_device_result_overall_table_user_xnjian'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('account', models.CharField(max_length=16, verbose_name='账号')),
                ('password', models.CharField(max_length=16, verbose_name='密码')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('create_time', models.DateField(blank=True, null=True, verbose_name='入职时间')),
                ('gender', models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别')),
                ('depart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.department')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.CharField(max_length=128, verbose_name='执行的命令')),
                ('config_file', models.FileField(upload_to=app02.models.config_backup_upload_to, verbose_name='配置文件')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('backup_status', models.CharField(choices=[('success', '成功'), ('fail', '失败')], default='success', max_length=10, verbose_name='备份状态')),
                ('failure_reason', models.TextField(blank=True, null=True, verbose_name='失败原因')),
                ('config_changed', models.CharField(blank=True, max_length=10, null=True, verbose_name='配置是否改变')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('dev', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app02.device_table', verbose_name='关联设备')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64, verbose_name='账号')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('name', models.CharField(blank=True, max_length=16, null=True, verbose_name='姓名')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='手机号')),
                ('depart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app02.department')),
            ],
        ),
    ]
