# Generated by Django 4.2.11 on 2026-07-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0009_xunjianrecord_expected_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='巡检时间')),
                ('device', models.CharField(max_length=50, verbose_name='设备名')),
                ('command', models.CharField(max_length=200, verbose_name='命令')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间')),
            ],
            options={
                'verbose_name': '巡检缺口',
                'indexes': [models.Index(fields=['time', 'device'], name='app02_inspe_time_785404_idx'), models.Index(fields=['created_at'], name='app02_inspe_created_838d87_idx')],
            },
        ),
    ]
