# Generated by Django 4.2.11 on 2026-07-24 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0010_inspectiongap'),
    ]

    operations = [
        migrations.AddField(
            model_name='anomalyrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='记录时间'),
        ),
        migrations.AddIndex(
            model_name='anomalyrecord',
            index=models.Index(fields=['created_at'], name='app02_anoma_created_964df1_idx'),
        ),
    ]
