# Generated by Django 4.2.11 on 2026-07-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0011_anomalyrecord_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newdevice',
            name='device_class',
            field=models.CharField(choices=[('ASW', '接入交换机'), ('CSW', '核心交换机'), ('LSW', '轻量交换机'), ('OASW', '带外接入交换机'), ('PSW', '汇聚交换机'), ('USW', '专线交换机'), ('DCI', '数据中心互联'), ('DSW', 'DCI交换机'), ('IDC', '出口交换机'), ('SRP', '业务路由器/设备'), ('FW', '防火墙'), ('WAF', 'WEB应用防火墙'), ('IPS', '入侵防御'), ('IDS', '入侵检测'), ('OTHER', '其他')], db_index=True, default='OTHER', help_text='由命名规则解析得出，替代手写 role 作为基础命令集真源', max_length=20, verbose_name='设备分类(命名规则)'),
        ),
    ]
