# Generated by Django 4.2.11 on 2026-03-29 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0011_alter_result_specific_table_config_changed'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='巡检项名称')),
                ('command', models.CharField(max_length=200, verbose_name='执行命令')),
                ('parser', models.CharField(choices=[('raw', '原始文本'), ('regex', '正则提取'), ('strip_ts', '去时间戳'), ('textfsm', 'TextFSM模板')], default='raw', max_length=30, verbose_name='解析器')),
                ('parser_config', models.JSONField(blank=True, null=True, verbose_name='解析器配置')),
                ('checker', models.CharField(choices=[('baseline', '基线文本对比'), ('threshold', '阈值判断'), ('count', '关键字计数'), ('contains', '包含检查'), ('custom', '自定义函数')], default='baseline', max_length=30, verbose_name='检查器')),
                ('checker_config', models.JSONField(blank=True, null=True, verbose_name='检查器配置')),
                ('error_note', models.CharField(default='请检查', max_length=200, verbose_name='异常提示')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时(秒)')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '巡检项',
            },
        ),
        migrations.CreateModel(
            name='DeviceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='分组名称')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='描述')),
                ('check_items', models.ManyToManyField(blank=True, related_name='groups', to='app02.checkitem', verbose_name='绑定巡检项')),
            ],
            options={
                'verbose_name': '设备分组(新)',
            },
        ),
        migrations.CreateModel(
            name='XunjianRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='巡检时间')),
                ('operator', models.CharField(max_length=50, verbose_name='操作人')),
                ('result', models.CharField(default='正常', max_length=20, verbose_name='巡检结果')),
                ('is_baseline', models.BooleanField(default=False, verbose_name='是否为基线')),
                ('device_count', models.IntegerField(default=0, verbose_name='巡检设备数')),
                ('check_count', models.IntegerField(default=0, verbose_name='执行巡检项数')),
                ('ok_devices', models.IntegerField(default=0, verbose_name='正常台数')),
                ('anomaly_devices', models.IntegerField(default=0, verbose_name='异常台数')),
                ('failed_devices', models.IntegerField(default=0, verbose_name='失败台数')),
            ],
            options={
                'verbose_name': '巡检记录(新)',
                'ordering': ['-time'],
            },
        ),
        migrations.CreateModel(
            name='NewDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='设备名')),
                ('ip', models.CharField(max_length=50, verbose_name='IP地址')),
                ('device_type', models.CharField(max_length=50, verbose_name='设备类型')),
                ('username', models.CharField(max_length=64, verbose_name='用户名')),
                ('password', models.CharField(max_length=64, verbose_name='密码')),
                ('extra', models.JSONField(blank=True, default=dict, help_text='JSON格式，如: {"ospf_nei": 9, "lldp_nei": 6}', verbose_name='扩展参数')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app02.devicegroup', verbose_name='所属分组')),
            ],
            options={
                'verbose_name': '设备(新)',
            },
        ),
        migrations.CreateModel(
            name='CheckSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='检查集名称')),
                ('description', models.TextField(blank=True, verbose_name='说明')),
                ('enabled', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('groups', models.ManyToManyField(blank=True, related_name='check_sets', to='app02.devicegroup', verbose_name='包含的设备分组')),
            ],
            options={
                'verbose_name': '检查集',
            },
        ),
        migrations.CreateModel(
            name='CheckResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='巡检时间')),
                ('device', models.CharField(max_length=50, verbose_name='设备名')),
                ('command', models.CharField(max_length=200, verbose_name='命令')),
                ('result', models.TextField(blank=True, null=True, verbose_name='命令输出')),
            ],
            options={
                'verbose_name': '命令结果(新)',
                'indexes': [models.Index(fields=['time', 'device', 'command'], name='app02_check_time_2b4ce7_idx')],
            },
        ),
        migrations.CreateModel(
            name='AnomalyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50, verbose_name='巡检时间')),
                ('device', models.CharField(max_length=50, verbose_name='设备名')),
                ('command', models.CharField(max_length=200, verbose_name='命令')),
                ('notes', models.CharField(blank=True, max_length=200, null=True, verbose_name='异常说明')),
                ('confirm', models.BooleanField(default=False, verbose_name='已确认')),
                ('baseline_val', models.TextField(blank=True, null=True, verbose_name='基线值')),
                ('current_val', models.TextField(blank=True, null=True, verbose_name='当前值')),
            ],
            options={
                'verbose_name': '异常记录(新)',
                'indexes': [models.Index(fields=['time', 'device'], name='app02_anoma_time_b467ca_idx')],
            },
        ),
    ]
