# Generated by Django 4.2.11 on 2026-07-31 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0013_checkitem_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anomalyrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='异常说明'),
        ),
        migrations.AlterField(
            model_name='checkitem',
            name='feature',
            field=models.CharField(choices=[('base', '基础'), ('ospf', 'OSPF'), ('bgp', 'BGP'), ('vrrp', 'VRRP'), ('irf', 'IRF'), ('m-lag', 'M-LAG'), ('rbm', 'RBM'), ('security', '安全域/策略'), ('lacp', '链路聚合'), ('nqa', 'NQA'), ('vpn', 'MPLS/VPN')], db_index=True, default='base', help_text='base=基础健康项(恒跑)；ospf/bgp/vrrp/irf/m-lag/rbm/security/lacp=协议特性项(需能力门控)', max_length=10, verbose_name='能力标签'),
        ),
    ]
