# Generated by Django 4.2.11 on 2026-07-31 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0014_alter_anomalyrecord_notes_alter_checkitem_feature'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmdbFlashStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_kb', models.BigIntegerField(blank=True, null=True, verbose_name='总容量(KB)')),
                ('used_kb', models.BigIntegerField(blank=True, null=True, verbose_name='已用(KB)')),
                ('free_kb', models.BigIntegerField(blank=True, null=True, verbose_name='剩余(KB)')),
                ('used_pct', models.FloatField(blank=True, null=True, verbose_name='使用率%')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_storage', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB Flash',
            },
        ),
        migrations.CreateModel(
            name='CmdbTransceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface', models.CharField(max_length=40, verbose_name='接口')),
                ('module_type', models.CharField(blank=True, default='', max_length=40, verbose_name='光模块型号')),
                ('vendor', models.CharField(blank=True, default='', max_length=40, verbose_name='厂商')),
                ('serial', models.CharField(blank=True, default='', max_length=40, verbose_name='序列号')),
                ('wavelength', models.CharField(blank=True, default='', max_length=10, verbose_name='波长(nm)')),
                ('distance', models.CharField(blank=True, default='', max_length=40, verbose_name='传输距离')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transceivers', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB光模块',
                'unique_together': {('device', 'interface')},
            },
        ),
        migrations.CreateModel(
            name='CmdbPowerSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('psu_id', models.CharField(max_length=10, verbose_name='电源编号')),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='状态')),
                ('psu_type', models.CharField(blank=True, default='', max_length=40, verbose_name='型号')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_supplies', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB电源',
                'unique_together': {('device', 'psu_id')},
            },
        ),
        migrations.CreateModel(
            name='CmdbFan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fan_id', models.CharField(max_length=10, verbose_name='风扇编号')),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='状态')),
                ('fan_type', models.CharField(blank=True, default='', max_length=40, verbose_name='型号')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fans', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB风扇',
                'unique_together': {('device', 'fan_id')},
            },
        ),
        migrations.CreateModel(
            name='CmdbBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(max_length=10, verbose_name='槽位号')),
                ('board_type', models.CharField(blank=True, default='', max_length=40, verbose_name='板卡类型')),
                ('status', models.CharField(blank=True, default='', max_length=20, verbose_name='状态')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to='app02.cmdbdevice', verbose_name='设备')),
            ],
            options={
                'verbose_name': 'CMDB板卡',
                'unique_together': {('device', 'slot')},
            },
        ),
    ]
