# Generated by Django 4.2.11 on 2026-08-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0015_cmdbflashstorage_cmdbtransceiver_cmdbpowersupply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_distance',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='光模块距离'),
        ),
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_ordering',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='光模块订货号'),
        ),
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_serial',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='光模块序列号'),
        ),
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_type',
            field=models.CharField(blank=True, default='', max_length=60, verbose_name='光模块型号'),
        ),
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_vendor',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='光模块厂商'),
        ),
        migrations.AddField(
            model_name='cmdbinterface',
            name='transceiver_wavelength',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='光模块波长(nm)'),
        ),
    ]
