"""
Django settings for xunjian_system1 project.

Generated by 'django-admin startproject' using Django 4.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'change-me-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DJANGO_DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.environ.get('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app02.apps.App02Config'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app02.middleware.auth.AuthMiddleware',

]

ROOT_URLCONF = 'xunjian_system1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'xunjian_system1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.environ.get('DB_NAME', 'xunjian_system'),
        'USER': os.environ.get('DB_USER', 'root'),
        'PASSWORD': os.environ.get('DB_PASSWORD', '7ujm^YHN'),
        'HOST': os.environ.get('DB_HOST', '127.0.0.1'),
        'PORT': int(os.environ.get('DB_PORT', '3306')),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'zh-hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ═══════════════════════════════════════════════════════
#  日志配置（覆盖 xunjian.* 命名空间）
# ═══════════════════════════════════════════════════════
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'simple': {
            'format': '{asctime} {levelname} {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'loggers': {
        'xunjian': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

# ═══════════════════════════════════════════════════════
#  巡检并发参数
# ═══════════════════════════════════════════════════════
XUNJIAN_CONCURRENCY = 32

# CheckResult / DiscoveryRecord / ComplianceResult 保留窗口（天），超期由后台维护线程自动清理
CHECKRESULT_RETENTION_DAYS = 90

MEDIA_ROOT = BASE_DIR / 'media'

MEDIA_URL = '/media/'

# ═══════════════════════════════════════════════════════
#  CMDB / 拓扑图谱（network-seek + Neo4j）联动配置
#  仅在使用 `manage.py rebuild_topology --push` 刷新 Neo4j 图时需要。
#  不配或置空则 rebuild_topology 只刷新本地 CMDB 与 fixture。
# ═══════════════════════════════════════════════════════
# network-seek 项目根目录（含 scripts/ 与 network_seek/ 包）
NETWORK_SEEK_DIR = r'C:/Users/ZSS/Desktop/network-seek'
# 用于运行 network-seek 脚本的 Python（建议其独立 venv 的解释器）
NETWORK_SEEK_PYTHON = r'C:/Users/ZSS/Desktop/network-seek/venv/Scripts/python.exe'
# Neo4j 连接（每站点一个容器不同 bolt 端口：知识城7687/化龙7688）
NEO4J_BOLT_URI = 'bolt://localhost:7687'
NEO4J_USER = 'neo4j'
NEO4J_PASSWORD = 'networkseek2024'

# ═══════════════════════════════════════════════════════
#  NetBox 联动（DCIM / IPAM）
#  不配或置空则 sync_netbox 仅导文件不推 API
# ═══════════════════════════════════════════════════════
NETBOX_URL = 'http://<内网IP>:8080'       # 改成实际内网 NetBox 地址
NETBOX_TOKEN = ''                          # NetBox UI → Profile → API Tokens
